### ISSUE TITLE
lemon pickup

### ISSUE THREAD

**Issue by ste-pool** [DavyK/cultivate#16]

**Comment by DavyK** [comment]
MINE

**Comment by DavyK** [comment]
Player now picks up the item in the pick ups group that they collide with. 

Should we instead stop the play from moving and make them press the button?

**Comment by Edward-Knight** [comment]
I like the idea of a "Press SPACE to pick up" tooltip appearing in the bottom corner when you're near a pickup


🍋🍋🍋🍋
🍋
🍋🍋🍋🍋
🍋
🍋🍋🍋🍋

**Comment by ste-pool** [comment]
I'm gonna take this because I think @DavyK is not working on this anymore?
